import { Player } from '@/types';

export const PLAYERS_DATA: Player[] = [
  {
    id: '1',
    name: 'AMIT MEHTA',
    mobileNumber: '9802441730',
    playingRole: 'Allrounder',
    wing: 'D-Wing',
    flatNumber: '707',
    dateOfBirth: '06-08-1977',
    age: 48,
    category: 'LEGEND',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Amit%20Mehta.jpg',
  },
  {
    id: '2',
    name: 'DR DATTATRAYA CHAUDHARI',
    mobileNumber: '9004438777',
    playingRole: 'Allrounder',
    wing: 'B-Wing',
    flatNumber: '1305',
    dateOfBirth: '01-05-1986',
    age: 39,
    category: 'LEGEND',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/DR-DATTA%20.jpeg',
  },
  {
    id: '3',
    name: 'DR. HARSH PATEL',
    mobileNumber: '8898593838',
    playingRole: 'Batsman',
    wing: 'B-Wing',
    flatNumber: '2007',
    dateOfBirth: '16-08-1985',
    age: 40,
    category: 'LEGEND',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Harsh%20Patel.jpeg',
  },
  {
    id: '4',
    name: 'KISHOR S JALGAONKAR',
    mobileNumber: '9820844665',
    playingRole: 'Allrounder',
    wing: 'D-Wing',
    flatNumber: '805',
    dateOfBirth: '04-07-1978',
    age: 47,
    category: 'LEGEND',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/KISHOR.jpeg',
  },
  {
    id: '5',
    name: 'PRAKASH JAJU',
    mobileNumber: '9920044594',
    playingRole: 'Bowler',
    wing: 'B-Wing',
    flatNumber: '1501',
    dateOfBirth: '15-11-1976',
    age: 49,
    category: 'LEGEND',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Prakash_Jaju.jpg',
  },
  {
    id: '6',
    name: 'RAJESH ANGRE',
    mobileNumber: '9867253292',
    playingRole: 'Allrounder',
    wing: 'A-Wing',
    flatNumber: '1207',
    dateOfBirth: '12-11-1966',
    age: 59,
    category: 'LEGEND',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Rajesh_Angre.jpg',
  },
  {
    id: '7',
    name: 'SUJIT SINGH',
    mobileNumber: '9930354125',
    playingRole: 'Allrounder',
    wing: 'B-Wing',
    flatNumber: '1103',
    dateOfBirth: '07-05-1979',
    age: 46,
    category: 'LEGEND',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/SUJIT_SINGH.jpeg',
  },
  {
    id: '8',
    name: 'ARTHAV JAJU',
    mobileNumber: '8779181125',
    playingRole: 'Allrounder',
    wing: 'B-Wing',
    flatNumber: '1501',
    dateOfBirth: '04-02-2006',
    age: 19,
    category: 'YOUNGSTAR',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/arthav%20jaju.jpg',
  },
  {
    id: '9',
    name: 'HITANSHU PATIL',
    mobileNumber: '7738796766',
    playingRole: 'Allrounder',
    wing: 'A-Wing',
    flatNumber: '1004',
    dateOfBirth: '12-01-2009',
    age: 16,
    category: 'YOUNGSTAR',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Hitanshu%20Patil.jpeg',
  },
  {
    id: '10',
    name: 'JAINIL CHAURASIA',
    mobileNumber: '9082474810',
    playingRole: 'Allrounder',
    wing: 'C-Wing',
    flatNumber: '1507',
    dateOfBirth: '29-03-2011',
    age: 14,
    category: 'YOUNGSTAR',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/JAINIL.jpeg',
  },
  {
    id: '11',
    name: 'JIYANSH SHARMA',
    mobileNumber: '8454029816',
    playingRole: 'Allrounder',
    wing: 'D-Wing',
    flatNumber: '1303',
    dateOfBirth: '13-11-2010',
    age: 15,
    category: 'YOUNGSTAR',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/JIYANSH%20SHARMA.jpeg',
  },
  {
    id: '12',
    name: 'JOSHUA DSOUZA',
    mobileNumber: '8424071109',
    playingRole: 'Allrounder',
    wing: 'C-Wing',
    flatNumber: '1601',
    dateOfBirth: '07-11-2009',
    age: 16,
    category: 'YOUNGSTAR',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Joshua.jpeg',
  },
  {
    id: '13',
    name: 'LUCKY SHUKLA',
    mobileNumber: '9137040296',
    playingRole: 'Allrounder',
    wing: 'A-Wing',
    flatNumber: '2002',
    dateOfBirth: '12-09-2008',
    age: 17,
    category: 'YOUNGSTAR',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Lakshya%20Shukla.jpg',
  },
  {
    id: '14',
    name: 'NIVRITT JANGID',
    mobileNumber: '8097614810',
    playingRole: 'Batsman',
    wing: 'B-Wing',
    flatNumber: '1507',
    dateOfBirth: '03-04-2009',
    age: 16,
    category: 'YOUNGSTAR',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Nivritt%20Jangid.jpeg',
  },
  {
    id: '15',
    name: 'SHAKTI PANDEY',
    mobileNumber: '6387219899',
    playingRole: 'Batsman',
    wing: 'A-Wing',
    flatNumber: '804',
    dateOfBirth: '15-09-2007',
    age: 18,
    category: 'YOUNGSTAR',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Shakti%20Pandey.jpg',
  },
  {
    id: '16',
    name: 'SHAURYA GURAV',
    mobileNumber: '8591658609',
    playingRole: 'Allrounder',
    wing: 'B-Wing',
    flatNumber: '1904',
    dateOfBirth: '30-10-2009',
    age: 16,
    category: 'YOUNGSTAR',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/SHAURYA%20GURAV.jpeg',
  },
  {
    id: '17',
    name: 'ASHISH SHETTY',
    mobileNumber: '7738952678',
    playingRole: 'Allrounder',
    wing: 'D-Wing',
    flatNumber: '705',
    dateOfBirth: '03-12-1992',
    age: 33,
    category: 'GOLD',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Ashish%20Shetty.jpeg',
  },
  {
    id: '18',
    name: 'DHARMENDRA CHAURASIA',
    mobileNumber: '9967282811',
    playingRole: 'Allrounder',
    wing: 'C-Wing',
    flatNumber: '1507',
    dateOfBirth: '15-01-1987',
    age: 38,
    category: 'GOLD',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/DHARMENDRA%20B%20CHAURASIA.jpg',
  },
  {
    id: '19',
    name: 'KRISH',
    mobileNumber: '7039977751',
    playingRole: 'Allrounder',
    wing: 'A-Wing',
    flatNumber: '1204',
    dateOfBirth: '23-07-1986',
    age: 39,
    category: 'GOLD',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/puneet%20krishnani.jpg',
  },
  {
    id: '20',
    name: 'PRAVIN CHOUDHARY',
    mobileNumber: '9819233416',
    playingRole: 'Allrounder',
    wing: 'B-Wing',
    flatNumber: '607',
    dateOfBirth: '19-12-1980',
    age: 44,
    category: 'GOLD',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Pravin_Choudhary_NEW.jpg',
  },
  {
    id: '21',
    name: 'RAHUL PANDEY',
    mobileNumber: '9029590379',
    playingRole: 'Allrounder',
    wing: 'B-Wing',
    flatNumber: '1208',
    dateOfBirth: '13-03-1988',
    age: 37,
    category: 'GOLD',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Rahul%20Pandey.jpg',
  },
  {
    id: '22',
    name: 'SAHIL MISHRA',
    mobileNumber: '8369792359',
    playingRole: 'Allrounder',
    wing: 'B-Wing',
    flatNumber: '1001',
    dateOfBirth: '29-07-2001',
    age: 24,
    category: 'GOLD',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/SAHIL%20MISHRA.jpeg',
  },
  {
    id: '23',
    name: 'SALIL',
    mobileNumber: '9833249235',
    playingRole: 'Allrounder',
    wing: 'C-Wing',
    flatNumber: '301',
    dateOfBirth: '21-07-1981',
    age: 44,
    category: 'GOLD',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/salil%20patil.jpg',
  },
  {
    id: '24',
    name: 'SAMIR PATIL',
    mobileNumber: '8879336292',
    playingRole: 'Allrounder',
    wing: 'C-Wing',
    flatNumber: '301',
    dateOfBirth: '08-10-1985',
    age: 40,
    category: 'GOLD',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/samir_patil.jpeg',
  },
  {
    id: '25',
    name: 'SATYAM',
    mobileNumber: '9699988803',
    playingRole: 'Allrounder',
    wing: 'B-Wing',
    flatNumber: '1304',
    dateOfBirth: '04-02-1992',
    age: 33,
    category: 'GOLD',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Satyam.jpeg',
  },
  {
    id: '26',
    name: 'SUMEET BIYANI',
    mobileNumber: '9773450178',
    playingRole: 'Allrounder',
    wing: 'D-Wing',
    flatNumber: '1708',
    dateOfBirth: '10-12-1986',
    age: 38,
    category: 'GOLD',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Sumeet%20Biyani.jpeg',
  },
  {
    id: '27',
    name: 'SUSHANT GUPTA',
    mobileNumber: '9819822585',
    playingRole: 'Allrounder',
    wing: 'A-Wing',
    flatNumber: '805',
    dateOfBirth: '22-11-1985',
    age: 40,
    category: 'GOLD',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Sushant%20Gupta.jpg',
  },
  {
    id: '28',
    name: 'VINAYAK SEMWAL',
    mobileNumber: '8286430095',
    playingRole: 'Allrounder',
    wing: 'A-Wing',
    flatNumber: '504',
    dateOfBirth: '01-11-1993',
    age: 32,
    category: 'GOLD',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/vinayak%20semwal.jpg',
  },
  {
    id: '29',
    name: 'AMARDEEP CHAURASIYA',
    mobileNumber: '9519741198',
    playingRole: 'Allrounder',
    wing: 'C-Wing',
    flatNumber: '1507',
    dateOfBirth: '16-06-1999',
    age: 26,
    category: 'SILVER',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Amardeep.jpeg',
  },
  {
    id: '30',
    name: 'AMIT DADHICH',
    mobileNumber: '9819243381',
    playingRole: 'Allrounder',
    wing: 'D-Wing',
    flatNumber: '1206',
    dateOfBirth: '15-01-1984',
    age: 41,
    category: 'SILVER',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Amit%20Dadhich.jpg',
  },
  {
    id: '31',
    name: 'ANIL KABRA',
    mobileNumber: '9172737370',
    playingRole: 'Batsman',
    wing: 'D-Wing',
    flatNumber: '1207',
    dateOfBirth: '12-09-1988',
    age: 37,
    category: 'SILVER',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Anil_Kabra.jpg',
  },
  {
    id: '32',
    name: 'ANUBHAV JHA',
    mobileNumber: '7982681191',
    playingRole: 'Allrounder',
    wing: 'A-Wing',
    flatNumber: '306',
    dateOfBirth: '16-07-2007',
    age: 18,
    category: 'SILVER',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Anubhav.jpeg',
  },
  {
    id: '33',
    name: 'AVIN BURICHA',
    mobileNumber: '9664095536',
    playingRole: 'Batsman',
    wing: 'D-Wing',
    flatNumber: '1205',
    dateOfBirth: '19-01-1994',
    age: 31,
    category: 'SILVER',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Avin%20Buricha.jpg',
  },
  {
    id: '34',
    name: 'BIRENDRA THAKUR',
    mobileNumber: '9987094047',
    playingRole: 'Batsman',
    wing: 'D-Wing',
    flatNumber: '1507',
    dateOfBirth: '12-03-1978',
    age: 47,
    category: 'SILVER',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Birendra%20Thakur.jpeg',
  },
  {
    id: '35',
    name: 'CHETAN PUROHIT',
    mobileNumber: '9930979964',
    playingRole: 'Batsman',
    wing: 'D-Wing',
    flatNumber: '1408',
    dateOfBirth: '08-05-1996',
    age: 29,
    category: 'SILVER',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Chetan_Purohit.jpeg',
  },
  {
    id: '36',
    name: 'DHARMIT JHUNJHUNWALA',
    mobileNumber: '7028055820',
    playingRole: 'Allrounder',
    wing: 'D-Wing',
    flatNumber: '602',
    dateOfBirth: '27-11-1992',
    age: 33,
    category: 'SILVER',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/DHARMIT_new.jpg',
  },
  {
    id: '37',
    name: 'JATIN KARKHUR',
    mobileNumber: '7999901988',
    playingRole: 'Allrounder',
    wing: 'B-Wing',
    flatNumber: '201',
    dateOfBirth: '04-11-2002',
    age: 23,
    category: 'SILVER',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/jatin%20Karkhur.jpg',
  },
  {
    id: '38',
    name: 'KARAN KHEMKA',
    mobileNumber: '9892989279',
    playingRole: 'Allrounder',
    wing: 'C-Wing',
    flatNumber: '1904',
    dateOfBirth: '25-11-1986',
    age: 39,
    category: 'SILVER',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Karan%20Khemka_new.jpeg',
  },
  {
    id: '39',
    name: 'KUSHAGRA AGARWAL',
    mobileNumber: '8369592447',
    playingRole: 'Batsman',
    wing: 'D-Wing',
    flatNumber: '802',
    dateOfBirth: '19-10-2006',
    age: 19,
    category: 'SILVER',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Kushagra%20Agarwal.jpeg',
  },
  {
    id: '40',
    name: 'LUV SINGH',
    mobileNumber: '8600621627',
    playingRole: 'Allrounder',
    wing: 'D-Wing',
    flatNumber: '1907',
    dateOfBirth: '13-07-1993',
    age: 32,
    category: 'SILVER',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Luv%20Singh.jpeg',
  },
  {
    id: '41',
    name: 'MANJEET SINGH RANA',
    mobileNumber: '7875305107',
    playingRole: 'Allrounder',
    wing: 'D-Wing',
    flatNumber: '601',
    dateOfBirth: '07-12-2001',
    age: 23,
    category: 'SILVER',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Manjeet%20Rana.jpg',
  },
  {
    id: '42',
    name: 'MANTHAN KASKAR',
    mobileNumber: '8169433135',
    playingRole: 'Allrounder',
    wing: 'A-Wing',
    flatNumber: '1408',
    dateOfBirth: '30-08-2008',
    age: 17,
    category: 'SILVER',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Manthan.jpg',
  },
  {
    id: '43',
    name: 'MAYANK JAIN',
    mobileNumber: '9029182687',
    playingRole: 'Batsman',
    wing: 'B-Wing',
    flatNumber: '706',
    dateOfBirth: '30-07-1991',
    age: 34,
    category: 'SILVER',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Mayank%20Jain.jpeg',
  },
  {
    id: '44',
    name: 'MOHIT',
    mobileNumber: '9004149078',
    playingRole: 'Allrounder',
    wing: 'A-Wing',
    flatNumber: '1408',
    dateOfBirth: '30-08-2008',
    age: 17,
    category: 'SILVER',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Mohit.jpeg',
  },
  {
    id: '45',
    name: 'NAMAN MAHANSARIA',
    mobileNumber: '9821087157',
    playingRole: 'Allrounder',
    wing: 'B-Wing',
    flatNumber: '308',
    dateOfBirth: '22-07-1991',
    age: 34,
    category: 'SILVER',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Naman%20Mahansaria.jpeg',
  },
  {
    id: '46',
    name: 'NANDPAL VASTAR',
    mobileNumber: '9892873896',
    playingRole: 'Allrounder',
    wing: 'C-Wing',
    flatNumber: '1208',
    dateOfBirth: '04-06-1982',
    age: 43,
    category: 'SILVER',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Nandpal.jpeg',
  },
  {
    id: '47',
    name: 'NITIN SHARMA',
    mobileNumber: '9773263644',
    playingRole: 'Allrounder',
    wing: 'A-Wing',
    flatNumber: '1302',
    dateOfBirth: '01-06-1988',
    age: 37,
    category: 'SILVER',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/NITIN_SHARMA.jpeg',
  },
  {
    id: '48',
    name: 'PRAVIN P',
    mobileNumber: '9699440363',
    playingRole: 'Allrounder',
    wing: 'C-Wing',
    flatNumber: '704',
    dateOfBirth: '19-03-1994',
    age: 31,
    category: 'SILVER',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Pravin%20P.jpg',
  },
  {
    id: '49',
    name: 'RAHUL PAREEK',
    mobileNumber: '8104052834',
    playingRole: 'Batsman',
    wing: 'D-Wing',
    flatNumber: '2007',
    dateOfBirth: '30-06-2001',
    age: 24,
    category: 'SILVER',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Rahul%20pareek.jpg',
  },
  {
    id: '50',
    name: 'RAJESH MISHRA',
    mobileNumber: '9702665804',
    playingRole: 'Allrounder',
    wing: 'B-Wing',
    flatNumber: '403',
    dateOfBirth: '11-09-1989',
    age: 36,
    category: 'SILVER',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Rajesh%20Mishra.jpeg',
  },
  {
    id: '51',
    name: 'RISHABH SINGH',
    mobileNumber: '9930054538',
    playingRole: 'Batsman',
    wing: 'B-Wing',
    flatNumber: '1004',
    dateOfBirth: '19-03-1995',
    age: 30,
    category: 'SILVER',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Rishabh%20singh.jpeg',
  },
  {
    id: '52',
    name: 'ROHAN MISHRA',
    mobileNumber: '8879393669',
    playingRole: 'Allrounder',
    wing: 'D-Wing',
    flatNumber: '101',
    dateOfBirth: '18-11-1987',
    age: 38,
    category: 'SILVER',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Rohan%20Mishra.jpg',
  },
  {
    id: '53',
    name: 'ROHIT MISHRA',
    mobileNumber: '8879721091',
    playingRole: 'Batsman',
    wing: 'D-Wing',
    flatNumber: '101',
    dateOfBirth: '18-11-1987',
    age: 38,
    category: 'SILVER',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/rohit%20mishra.jpg',
  },
  {
    id: '54',
    name: 'ROSHAN BHANUSHALI',
    mobileNumber: '9136363411',
    playingRole: 'Allrounder',
    wing: 'D-Wing',
    flatNumber: '1106',
    dateOfBirth: '06-08-2003',
    age: 22,
    category: 'SILVER',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/ROSHAN.jpeg',
  },
  {
    id: '55',
    name: 'SANJAY MORE',
    mobileNumber: '7738047088',
    playingRole: 'Batsman',
    wing: 'D-Wing',
    flatNumber: '107',
    dateOfBirth: '15-09-1980',
    age: 45,
    category: 'SILVER',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/SANJAY_MORE%20.jpeg',
  },
  {
    id: '56',
    name: 'SAURABH PODDAR',
    mobileNumber: '9324744859',
    playingRole: 'Allrounder',
    wing: 'C-Wing',
    flatNumber: '1703',
    dateOfBirth: '09-09-1988',
    age: 37,
    category: 'SILVER',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Saurabh%20poddar.jpg',
  },
  {
    id: '57',
    name: 'SHORYA ADHIKARY',
    mobileNumber: '8928636516',
    playingRole: 'Batsman',
    wing: 'D-Wing',
    flatNumber: '704',
    dateOfBirth: '13-03-2007',
    age: 18,
    category: 'SILVER',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Shorya%20Adhikary.jpg',
  },
  {
    id: '58',
    name: 'UTTAM THAKUR',
    mobileNumber: '9930672236',
    playingRole: 'Allrounder',
    wing: 'B-Wing',
    flatNumber: '101',
    dateOfBirth: '01-02-1992',
    age: 33,
    category: 'SILVER',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/UTTAM%20THAKUR.jpg',
  },
  {
    id: '59',
    name: 'VIJIT NAIR',
    mobileNumber: '9892728926',
    playingRole: 'Batsman',
    wing: 'C-Wing',
    flatNumber: '1303',
    dateOfBirth: '01-12-1987',
    age: 38,
    category: 'SILVER',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Vijit%20Nair.jpeg',
  },
  {
    id: '60',
    name: 'VIRENDRA PAL',
    mobileNumber: '8419913143',
    playingRole: 'Batsman',
    wing: 'C-Wing',
    flatNumber: '906',
    dateOfBirth: '29-09-1997',
    age: 28,
    category: 'SILVER',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Virendra%20Pal.jpg',
  },
  {
    id: '61',
    name: 'VIVEKSINGH BHADOURIA',
    mobileNumber: '9867797382',
    playingRole: 'Allrounder',
    wing: 'C-Wing',
    flatNumber: '1305',
    dateOfBirth: '12-12-1984',
    age: 40,
    category: 'SILVER',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/vivek%20bhadouria.jpeg',
  },
  {
    id: '62',
    name: 'AASHUTOSH SHUKLA',
    mobileNumber: '8169224244',
    playingRole: 'Batsman',
    wing: 'A-Wing',
    flatNumber: '2002',
    dateOfBirth: '10-04-1983',
    age: 42,
    category: 'BRONZE',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/ASHUTOSH_SHUKLA_new.jpg',
  },
  {
    id: '63',
    name: 'AMAN KARIWALA',
    mobileNumber: '8976009684',
    playingRole: 'Allrounder',
    wing: 'C-Wing',
    flatNumber: '1407',
    dateOfBirth: '14-09-1994',
    age: 31,
    category: 'BRONZE',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Aman%20Kariwalaa.jpg',
  },
  {
    id: '64',
    name: 'ANAND PANDEY',
    mobileNumber: '8291670622',
    playingRole: 'Batsman',
    wing: 'C-Wing',
    flatNumber: '707',
    dateOfBirth: '20-12-1990',
    age: 34,
    category: 'BRONZE',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Anand%20Pandey.jpg',
  },
  {
    id: '65',
    name: 'BRIJESH SOLANKI',
    mobileNumber: '8097543539',
    playingRole: 'Batsman',
    wing: 'B-Wing',
    flatNumber: '104',
    dateOfBirth: '17-11-1986',
    age: 39,
    category: 'BRONZE',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Brijesh_Solanki.jpeg',
  },
  {
    id: '66',
    name: 'DEEPAK AHIRE',
    mobileNumber: '9004479790',
    playingRole: 'Allrounder',
    wing: 'D-Wing',
    flatNumber: '1308',
    dateOfBirth: '18-07-1984',
    age: 41,
    category: 'BRONZE',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Deepak%20Ahire.jpg',
  },
  {
    id: '67',
    name: 'DINESH SHARMA',
    mobileNumber: '9167726097',
    playingRole: 'Bowler',
    wing: 'D-Wing',
    flatNumber: '1504',
    dateOfBirth: '28-05-1989',
    age: 36,
    category: 'BRONZE',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/dinesh%20sharma.jpg',
  },
  {
    id: '68',
    name: 'DR PARAS GUPTA',
    mobileNumber: '9870751497',
    playingRole: 'Allrounder',
    wing: 'D-Wing',
    flatNumber: '1306',
    dateOfBirth: '08-07-1986',
    age: 39,
    category: 'BRONZE',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Dr%20Paras%20Gupta.jpeg',
  },
  {
    id: '69',
    name: 'GOPAL PRAJAPATI',
    mobileNumber: '8779673593',
    playingRole: 'Allrounder',
    wing: 'A-Wing',
    flatNumber: '1805',
    dateOfBirth: '29-07-1985',
    age: 40,
    category: 'BRONZE',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/GOPAL%20LAL%20PRAJAPATI.jpg',
  },
  {
    id: '70',
    name: 'HEMANT SHARMA',
    mobileNumber: '9987907989',
    playingRole: 'Allrounder',
    wing: 'A-Wing',
    flatNumber: '1202',
    dateOfBirth: '02-01-1991',
    age: 34,
    category: 'BRONZE',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/HEMANT%20SHARMA_NEW.jpeg',
  },
  {
    id: '71',
    name: 'HEMIN MODI',
    mobileNumber: '9819822281',
    playingRole: 'Batsman',
    wing: 'A-Wing',
    flatNumber: '1206',
    dateOfBirth: '11-11-1979',
    age: 46,
    category: 'BRONZE',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Hemin.jpeg',
  },
  {
    id: '72',
    name: 'HITESH PUROHIT',
    mobileNumber: '9870687038',
    playingRole: 'Batsman',
    wing: 'D-Wing',
    flatNumber: '1405',
    dateOfBirth: '10-07-1989',
    age: 36,
    category: 'BRONZE',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/HITESH_PUROHIT.jpeg',
  },
  {
    id: '73',
    name: 'MIKHIL ANGRE',
    mobileNumber: '9324068377',
    playingRole: 'Allrounder',
    wing: 'A-Wing',
    flatNumber: '1207',
    dateOfBirth: '28-08-2003',
    age: 22,
    category: 'BRONZE',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Mikhil%20Angre.jpg',
  },
  {
    id: '74',
    name: 'MIT SACHDEV',
    mobileNumber: '9833242729',
    playingRole: 'Allrounder',
    wing: 'C-Wing',
    flatNumber: '1802',
    dateOfBirth: '21-10-1992',
    age: 33,
    category: 'BRONZE',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Mit%20Sachdev_NEW.jpg',
  },
  {
    id: '75',
    name: 'PIYUSH LAKHOTIA',
    mobileNumber: '9137896135',
    playingRole: 'Allrounder',
    wing: 'B-Wing',
    flatNumber: '103',
    dateOfBirth: '08-09-2002',
    age: 23,
    category: 'BRONZE',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Piyush%20lakhotia.jpeg',
  },
  {
    id: '76',
    name: 'PRABHAKAR',
    mobileNumber: '9892643161',
    playingRole: 'Allrounder',
    wing: 'A-Wing',
    flatNumber: '1504',
    dateOfBirth: '18-08-1986',
    age: 39,
    category: 'BRONZE',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/PRABHAKAR.jpeg',
  },
  {
    id: '77',
    name: 'PRINCE',
    mobileNumber: '9820513450',
    playingRole: 'Bowler',
    wing: 'A-Wing',
    flatNumber: '1204',
    dateOfBirth: '01-01-1990',
    age: 35,
    category: 'BRONZE',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/PRINCE.jpg',
  },
  {
    id: '78',
    name: 'RAHUL BAJAJ',
    mobileNumber: '8452833629',
    playingRole: 'Batsman',
    wing: 'C-Wing',
    flatNumber: '1502',
    dateOfBirth: '18-10-1991',
    age: 34,
    category: 'BRONZE',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Rahul%20bajaj.jpg',
  },
  {
    id: '79',
    name: 'RAVI BHANDARI',
    mobileNumber: '8097932009',
    playingRole: 'Allrounder',
    wing: 'A-Wing',
    flatNumber: '1901',
    dateOfBirth: '13-05-1988',
    age: 37,
    category: 'BRONZE',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Ravi%20bhandari.jpg',
  },
  {
    id: '80',
    name: 'RAVI KABRA',
    mobileNumber: '8291494160',
    playingRole: 'Batsman',
    wing: 'D-Wing',
    flatNumber: '1207',
    dateOfBirth: '01-12-1990',
    age: 35,
    category: 'BRONZE',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/RaviKabra_NEW.jpg',
  },
  {
    id: '81',
    name: 'RONAK PARMAR',
    mobileNumber: '9321169896',
    playingRole: 'Allrounder',
    wing: 'A-Wing',
    flatNumber: '1202',
    dateOfBirth: '22-05-1986',
    age: 39,
    category: 'BRONZE',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Ronak%20Parmar.jpg',
  },
  {
    id: '82',
    name: 'SANDESH BALWANT PATIL',
    mobileNumber: '9819513752',
    playingRole: 'Allrounder',
    wing: 'B-Wing',
    flatNumber: '1508',
    dateOfBirth: '10-02-1985',
    age: 40,
    category: 'BRONZE',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/sandesh%20patil.jpg',
  },
  {
    id: '83',
    name: 'SHAILESH JHA',
    mobileNumber: '8850297768',
    playingRole: 'Allrounder',
    wing: 'B-Wing',
    flatNumber: '1504',
    dateOfBirth: '13-02-1985',
    age: 40,
    category: 'BRONZE',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/SHAILESH_JHS.jpg',
  },
  {
    id: '84',
    name: 'SOUMITRA PATOLE',
    mobileNumber: '9702383567',
    playingRole: 'Allrounder',
    wing: 'C-Wing',
    flatNumber: '2006',
    dateOfBirth: '14-09-1994',
    age: 31,
    category: 'BRONZE',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Soumitra%20Patole.jpeg',
  },
  {
    id: '85',
    name: 'SUKHDEV JOSHI',
    mobileNumber: '9412992994',
    playingRole: 'Allrounder',
    wing: 'A-Wing',
    flatNumber: '504',
    dateOfBirth: '09-03-1998',
    age: 27,
    category: 'BRONZE',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Sukhdev%20Joshi.jpeg',
  },
  {
    id: '86',
    name: 'SURAJ VERMA',
    mobileNumber: '9821240181',
    playingRole: 'Allrounder',
    wing: 'B-Wing',
    flatNumber: '802',
    dateOfBirth: '05-03-1991',
    age: 34,
    category: 'BRONZE',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Suraj%20Verma.jpg',
  },
  {
    id: '87',
    name: 'UMESH JAIN',
    mobileNumber: '8433625195',
    playingRole: 'Allrounder',
    wing: 'C-Wing',
    flatNumber: '1404',
    dateOfBirth: '27-10-1997',
    age: 28,
    category: 'BRONZE',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/UMESH%20JAIN.jpeg',
  },
  {
    id: '88',
    name: 'VISHESH',
    mobileNumber: '9372503732',
    playingRole: 'Allrounder',
    wing: 'C-Wing',
    flatNumber: '503',
    dateOfBirth: '02-08-2003',
    age: 22,
    category: 'BRONZE',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Vishesh.jpg',
  },
  {
    id: '90',
    name: 'SUNIL RAVANI',
    mobileNumber: '9819488656',
    playingRole: 'Bowler',
    wing: 'C-Wing',
    flatNumber: '1806',
    dateOfBirth: '09-11-1978',
    age: 47,
    category: 'LEGEND',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Sunil%20Ravani.jpeg',
  },
  {
    id: '91',
    name: 'SIDDHESH ANGCHEKAR',
    mobileNumber: '9619995546',
    playingRole: 'Allrounder',
    wing: 'C-Wing',
    flatNumber: '608',
    dateOfBirth: '21-06-1988',
    age: 37,
    category: 'GOLD',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Siddhesh%20Angchekar.jpg',
  },
  {
    id: '92',
    name: 'VISHAL VERMA',
    mobileNumber: '9172987417',
    playingRole: 'Bowler',
    wing: 'B-Wing',
    flatNumber: '802',
    dateOfBirth: '02-01-1990',
    age: 35,
    category: 'BRONZE',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Vishal_Verma.jpg',
  },
  {
    id: '93',
    name: 'SANDIP VORA',
    mobileNumber: '9833145626',
    playingRole: 'Batsman',
    wing: 'C-Wing',
    flatNumber: '1705',
    dateOfBirth: '26-04-1984',
    age: 41,
    category: 'SILVER',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/SANDIP_VORA.jpeg',
  },
  {
    id: '94',
    name: 'PRITISH BHATTI',
    mobileNumber: '8097147777',
    playingRole: 'Allrounder',
    wing: 'C-Wing',
    flatNumber: '2008',
    dateOfBirth: '14-04-1984',
    age: 41,
    category: 'BRONZE',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Pritish%20bhatti.jpeg',
  },
  {
    id: '95',
    name: 'MANAV CHOUDHARY',
    mobileNumber: '9930295886',
    playingRole: 'Batsman',
    wing: 'B-Wing',
    flatNumber: '607',
    dateOfBirth: '24-09-2009',
    age: 16,
    category: 'BRONZE',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Manav%20Choudhary.jpeg',
  },
  {
    id: '96',
    name: 'CHERISH JAIN',
    mobileNumber: '9833292195',
    playingRole: 'Allrounder',
    wing: 'C-Wing',
    flatNumber: '1404',
    dateOfBirth: '04-04-1992',
    age: 33,
    category: 'BRONZE',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/CHERIS_JAIN_NEW.jpeg',
  },
  {
    id: '97',
    name: 'PRATHAM PATIL',
    mobileNumber: '8657336766',
    playingRole: 'Allrounder',
    wing: 'A-Wing',
    flatNumber: '1004',
    dateOfBirth: '18-12-2003',
    age: 22,
    category: 'SILVER',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Prathamesh%20Patil.jpeg',
  },
  {
    id: 'player-1765442342954',
    name: 'UJJAWAL M JHA',
    mobileNumber: '9372553623',
    playingRole: 'Allrounder',
    wing: 'B-Wing',
    flatNumber: '1504',
    dateOfBirth: '2008-03-17',
    age: 17,
    category: 'GOLD',
    imageUrl:
      'https://xsltm76ydtkqpepc.public.blob.vercel-storage.com/Ujjawal%20Jha.jpg',
  },
];
